"""
Plate diagram for the BSTS NegBinomial model.

Two outputs:
  results/bsts/plate_diagram.png        — custom hand-laid matplotlib version (used in blog)
  results/bsts/plate_diagram_pymc.png   — auto-generated by pm.model_to_graphviz (reference)
"""
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Circle, FancyBboxPatch
import numpy as np
import pandas as pd
import pymc as pm
from utils import load_observed_data
import model
import sys
import os

if len(sys.argv) > 1:
    mode = sys.argv[1]
else:
    mode = model.MODE

use_daily_gp = ("daily_gp" in mode or mode == "bsts_daily_gp")

# ── 1. PyMC auto-diagram (reference) ─────────────────────────────────────────
df = load_observed_data()
df["y"] = df["PM2p5_censored"].astype(int)
df["phase_numeric"] = df["phase"].map({"A": 0, "B": -1})
df["phase_occurrence"] = df["phase"] + df["period"].astype(int).astype(str)
df = df.sort_values("datetime")
df["session_in_phase"] = df.groupby("phase_occurrence")["datetime_of_experiment"].transform(
    lambda x: (x - x.min()).dt.total_seconds() / (24 * 3600)
)

model = model.get_pymc_bsts_model(df, use_daily_gp=use_daily_gp)
graph = pm.model_to_graphviz(model)
os.makedirs(f"results/{mode}", exist_ok=True)
graph.render(f"results/{mode}/plate_diagram_pymc", format="png", cleanup=True)
print(f"Saved results/{mode}/plate_diagram_pymc.png")


# ── 2. Custom matplotlib diagram (blog) ──────────────────────────────────────
fig, ax = plt.subplots(figsize=(11, 8))
ax.set_xlim(0, 11)
ax.set_ylim(0, 8.5)
ax.set_aspect("equal")
ax.axis("off")

R = 0.38  # node radius


def node(x, y, label, observed=False, deterministic=False, fs=11):
    fc = "#d0d0d0" if observed else "white"
    c = Circle((x, y), R, fc=fc, ec="black", lw=1.6, zorder=5)
    ax.add_patch(c)
    if deterministic:
        c2 = Circle((x, y), R - 0.09, fc="none", ec="black", lw=0.9, zorder=6)
        ax.add_patch(c2)
    ax.text(x, y, label, ha="center", va="center", fontsize=fs, zorder=7)


def plate(x, y, w, h, label, corner="bottom-right"):
    rect = FancyBboxPatch(
        (x, y), w, h,
        boxstyle="round,pad=0.12",
        fc="none", ec="#777777", lw=1.4, ls="--", zorder=1,
    )
    ax.add_patch(rect)
    v, ha = corner.split("-")
    tx = (x + w - 0.15) if ha == "right" else (x + 0.15)
    ty = (y + h - 0.15) if v == "top" else (y + 0.15)
    va = "top" if v == "top" else "bottom"
    ax.text(tx, ty, label,
            ha=ha, va=va, fontsize=9, color="#555555", style="italic", zorder=8)


def arrow(x1, y1, x2, y2):
    dx, dy = x2 - x1, y2 - y1
    d = np.hypot(dx, dy)
    ux, uy = dx / d, dy / d
    ax.annotate(
        "", xy=(x2 - ux * R, y2 - uy * R),
        xytext=(x1 + ux * R, y1 + uy * R),
        arrowprops=dict(arrowstyle="->", color="black", lw=1.3),
        zorder=4,
    )


# plates  — outer stops below global nodes; labels at top corners (clear space)
plate(0.35, 0.9, 10.3, 6.1, r"$j = 1 \ldots J$   (session)",      corner="top-left")
plate(0.75, 1.1, 9.1,  4.0, r"$i = 1 \ldots N_j$   (observation)", corner="top-right")

# global nodes
GLOB_Y = 7.8
node(1.5, GLOB_Y, r"$\mu$",                fs=12)
node(3.2, GLOB_Y, r"$\mu_{\log\gamma}$",   fs=10)
node(5.0, GLOB_Y, r"$\sigma_\gamma$",      fs=10)
node(7.0, GLOB_Y, r"$\sigma_\varepsilon$", fs=10)
node(9.2, GLOB_Y, r"$\phi$",               fs=12)

# session-level nodes
SES_Y = 6.4
node(3.2, SES_Y, r"$\tilde{\gamma}_j$", fs=10)
node(5.0, SES_Y, r"$\gamma_j$",         deterministic=True, fs=11)
node(7.5, SES_Y, r"$\text{init}_j$",    fs=10)

# observation-level nodes
OBS_Y1, OBS_Y2 = 4.6, 2.8
node(1.5, OBS_Y1, r"$P_i$",             observed=True,      fs=11)
node(7.0, OBS_Y1, r"$\varepsilon_i$",                       fs=10)
node(7.5, OBS_Y2, r"$L_{i,j}$",        deterministic=True, fs=10)
node(5.0, OBS_Y2, r"$\lambda_i$",      deterministic=True, fs=11)
node(8.0, 1.5,    r"$y_i$",            observed=True,      fs=12)

# arrows
arrow(3.2, GLOB_Y, 5.0, SES_Y)   # mu_log_gamma → gamma_j
arrow(5.0, GLOB_Y, 5.0, SES_Y)   # sigma_gamma  → gamma_j
arrow(3.2, SES_Y,  5.0, SES_Y)   # gamma_tilde  → gamma_j
arrow(5.0, SES_Y,  5.0, OBS_Y2)  # gamma_j      → lambda_i  (straight down)
arrow(7.5, SES_Y,  7.5, OBS_Y2)  # init_j       → L_{i,j}   (straight down)
arrow(1.5, GLOB_Y, 5.0, OBS_Y2)  # mu           → lambda_i
arrow(7.0, GLOB_Y, 7.0, OBS_Y1)  # sigma_eps    → innovations
arrow(9.2, GLOB_Y, 8.0, 1.5)     # phi          → y_i
arrow(1.5, OBS_Y1, 5.0, OBS_Y2)  # P_i          → lambda_i
arrow(7.0, OBS_Y1, 7.5, OBS_Y2)  # innovations  → L_{i,j}
arrow(7.5, OBS_Y2, 5.0, OBS_Y2)  # L_{i,j}      → lambda_i
arrow(5.0, OBS_Y2, 8.0, 1.5)     # lambda_i     → y_i

# legend
lx, ly = 0.5, 0.25
for fc, label in [("white", "latent"), ("#d0d0d0", "observed / data")]:
    c = Circle((lx, ly), 0.18, fc=fc, ec="black", lw=1.2, zorder=5)
    ax.add_patch(c)
    ax.text(lx + 0.3, ly, label, va="center", fontsize=9)
    lx += 2.2
c1 = Circle((lx, ly), 0.18, fc="white", ec="black", lw=1.2, zorder=5)
c2 = Circle((lx, ly), 0.10, fc="none",  ec="black", lw=0.8, zorder=6)
ax.add_patch(c1); ax.add_patch(c2)
ax.text(lx + 0.3, ly, "deterministic", va="center", fontsize=9)

plt.tight_layout()
plt.savefig(f"results/{mode}/plate_diagram.png", dpi=150, bbox_inches="tight", facecolor="white")
print(f"Saved results/{mode}/plate_diagram.png")

